### ISSUE TITLE
Regression: Generate links for all stores

### ISSUE THREAD

**Issue by jef** [jef/streetmerchant#694]
### Description

Currently, when `streetmerchant` starts up, links are generated for various stores. This behavior shouldn't happen if the user doesn't use those stores.

Refs:

- https://github.com/jef/streetmerchant/issues/683
- https://github.com/jef/streetmerchant/issues/691#issuecomment-722660867

### Possible solution

Make sure only links are generated for stores selected.

**Comment by garza-utsa** [comment]
@jef I was able to get the develop branch searching again by disabling the amazon-uk store, there only seems to be three link entries in there (one test and two ps5 sony), it was causing a hang after displaying "Failed to parse card: PNY GeForce ..." error line.

Is there a reason why links are generated for stores not even selected in the first place (I'm in the US with only 'newegg,amazon,bestbuy' set in my stores.

**Comment by garza** [comment]
@jef I was able to get the develop branch searching again by disabling the amazon-uk store, there only seems to be three link entries in there (one test and two ps5 sony), it was causing a hang after displaying "Failed to parse card: PNY GeForce ..." error line.

**Comment by jef** [comment]
Yeah, this is part of the regression of building links. I haven't spent anytime working on it, but should be fixed in the near future! Thanks for the comment, it will be helpful.

**Comment by taefighter** [comment]
Is there a workaround available for this? I have not been able to use streetmerchant for a few days because of this issue. I just get a 
"failed to parse..." error and the application stops.

**Comment by garza** [comment]
@taefighter do a git pull on main, i haven't had a problem since Friday with the latest code

**Comment by jef** [comment]
> Is there a workaround available for this? I have not been able to use streetmerchant for a few days because of this issue. I just get a
> "failed to parse..." error and the application stops.

This prohibit from the app from running at all. It just slows down and shows errors at startup.

**Comment by taefighter** [comment]
> @taefighter do a git pull on main, i haven't had a problem since Friday with the latest code

Thank you for letting me know. I am still getting the parsing error at startup. However, what @jef said tells me I wasn't giving the app enough time to process. I am leaving it running for a while to see if it will work past the errors at the start. Thank you!
